version: '3'

services:
  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v0.4.1-victorialogs
    volumes:
      - ./vlogs-db:/vlogs-db
    ports:
      - '9428:9428'
    command:
      - -storageDataPath=/vlogs-db
      - -loggerFormat=json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10

  vector:
    image: docker.io/timberio/vector:0.33.X-debian
    restart: on-failure
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - .:/opt
    user: root
    ports:
      - '8686:8686'
      - '8787:8787'
    depends_on:
      victorialogs:
        condition: service_healthy
    entrypoint:
      - /bin/sleep
      - infinity
