[api]
  enabled = true
  address = "0.0.0.0:8686"

[sources.benchmark]
  type = "stdin"

[transforms.msg_parser]
  type = "remap"
  inputs = ["benchmark"]
  source = '''
  .log = parse_json!(.message)
  del(.message)
  '''

[sinks.vlogs_benchmark]
  type = "http"
  inputs = [ "msg_parser" ]
  uri = "http://victorialogs:9428/insert/elasticsearch/"
  method = "POST"
  encoding = "json"
  healthcheck.enabled = false

  [sinks.vlogs_benchmark.request.headers]
    AccountID = "0"
    ProjectID = "0"

